[package]
name = "schema_fetch"
version = "0.1.0"
edition = "2024"

[dependencies]
pale = "0.1.0"
tokio = { version = "1.48", features = ["macros", "rt-multi-thread"] }
serde_json = "1.0"
dotenvy = "0.15.7"
serde = "1.0.228"
