[package]
name = "mc-rpc"
description = "Generated JSON RPC Bindings for Minecraft Server Management Protocol Client"
authors = ["VilleOlof"]
license = "MIT"
version = "0.1.1"
edition = "2024"
keywords = ["minecraft", "rpc", "json", "client"]
repository = "https://github.com/VilleOlof/mc-rpc"
exclude = ["schema_fetch"]

[dependencies]
pale = { git = "https://github.com/Xaeroxe/pale.git", rev = "9801a22d29d043388c1b78553e0add262de9b164" }
serde = { version = "1.0", features = ["derive"] }
tokio-stream = { version = "0.1.17", features = ["sync"] }
serde_json = "1.0"

[build-dependencies]
build-rs = "0.3.2"
serde_json = "1.0"

[workspace]
members = ["schema_fetch"]

[features]
default = ["all_versions"]
all_versions = [
    "protocol_version_1_0_0",
    "protocol_version_2_0_0"
]
protocol_version_1_0_0 = []
protocol_version_2_0_0 = []
